import pandas as pd
import numpy as np

def run_backtest_simulation(
    df: pd.DataFrame, 
    generate_signals_fn, 
    params: dict = None, 
    initial_capital: float = 100000.0,
    brokerage_per_trade: float = 20.0,
    slippage_pct: float = 0.0005,
    stt_tax_pct: float = 0.00025
) -> dict:
    """
    Strategy-agnostic backtesting execution engine for studio.trade.
    Simulates trades bar-by-bar based on signals generated by user strategy code.
    """
    if params is None:
        params = {}

    df_copy = df.copy()
    
    # Execute strategy code to get signals (-1, 0, 1)
    try:
        raw_signals = generate_signals_fn(df_copy, params)
        if not isinstance(raw_signals, pd.Series):
            raw_signals = pd.Series(raw_signals, index=df_copy.index)
    except Exception as e:
        raise RuntimeError(f"Runtime error while executing strategy code: {e}")

    df_copy['signal'] = raw_signals.fillna(0).astype(int)

    # Shift signal by 1 bar to prevent lookahead bias (trade executes on NEXT open/close)
    df_copy['pos'] = df_copy['signal'].shift(1).fillna(0)

    trades = []
    current_pos = 0 # 0: Cash, 1: Long, -1: Short
    entry_price = 0.0
    entry_date = None
    cash = initial_capital
    equity_curve = []

    for i in range(len(df_copy)):
        date = df_copy.index[i]
        price = df_copy['close'].iloc[i]
        target_pos = df_copy['pos'].iloc[i]

        # Check if position changes
        if target_pos != current_pos:
            # 1. Close existing position if any
            if current_pos != 0:
                exit_price = price * (1 - slippage_pct) if current_pos > 0 else price * (1 + slippage_pct)
                pnl_pct = (exit_price - entry_price) / entry_price if current_pos > 0 else (entry_price - exit_price) / entry_price
                
                trade_gross = cash * pnl_pct
                trade_costs = brokerage_per_trade + (cash * stt_tax_pct)
                trade_net = trade_gross - trade_costs

                cash += trade_net

                trades.append({
                    "trade_num": len(trades) + 1,
                    "type": "LONG" if current_pos > 0 else "SHORT",
                    "entry_date": str(entry_date),
                    "exit_date": str(date),
                    "entry_price": round(entry_price, 2),
                    "exit_price": round(exit_price, 2),
                    "pnl_pct": round(pnl_pct * 100, 2),
                    "net_pnl": round(trade_net, 2),
                    "capital_after": round(cash, 2)
                })

            # 2. Open new position if target_pos != 0
            if target_pos != 0:
                entry_price = price * (1 + slippage_pct) if target_pos > 0 else price * (1 - slippage_pct)
                entry_date = date
                cash -= brokerage_per_trade # Entry fee
            
            current_pos = target_pos

        # Track mark-to-market equity
        if current_pos != 0:
            unrealized = (price - entry_price) / entry_price if current_pos > 0 else (entry_price - price) / entry_price
            current_equity = cash + (cash * unrealized)
        else:
            current_equity = cash

        equity_curve.append(current_equity)

    df_copy['equity'] = equity_curve

    # Compute key quantitative metrics
    total_return_pct = ((cash - initial_capital) / initial_capital) * 100
    buy_and_hold_pct = ((df_copy['close'].iloc[-1] - df_copy['close'].iloc[0]) / df_copy['close'].iloc[0]) * 100

    # Drawdown calculation
    equity_series = pd.Series(equity_curve, index=df_copy.index)
    peak = equity_series.cummax()
    drawdown = (equity_series - peak) / peak
    max_drawdown_pct = float(drawdown.min()) * 100

    # Win rate & profit factor
    winning_trades = [t for t in trades if t['net_pnl'] > 0]
    losing_trades = [t for t in trades if t['net_pnl'] <= 0]

    win_rate_pct = (len(winning_trades) / len(trades) * 100) if trades else 0.0
    gross_profits = sum(t['net_pnl'] for t in winning_trades)
    gross_losses = abs(sum(t['net_pnl'] for t in losing_trades))
    profit_factor = (gross_profits / gross_losses) if gross_losses > 0 else (gross_profits if gross_profits > 0 else 1.0)

    # Sharpe ratio estimate (daily risk-free rate ~5% annualized)
    daily_returns = equity_series.pct_change().dropna()
    mean_ret = daily_returns.mean()
    std_ret = daily_returns.std()
    sharpe = float((mean_ret / (std_ret + 1e-10)) * np.sqrt(252)) if std_ret > 0 else 0.0

    return {
        "summary": {
            "initial_capital": round(initial_capital, 2),
            "final_capital": round(cash, 2),
            "total_return_pct": round(total_return_pct, 2),
            "buy_and_hold_pct": round(buy_and_hold_pct, 2),
            "win_rate_pct": round(win_rate_pct, 2),
            "max_drawdown_pct": round(max_drawdown_pct, 2),
            "profit_factor": round(profit_factor, 2),
            "sharpe_ratio": round(sharpe, 2),
            "total_trades": len(trades),
            "winning_trades": len(winning_trades),
            "losing_trades": len(losing_trades),
        },
        "trades": trades,
        "equity_curve": df_copy[['close', 'equity']].copy()
    }
